server:
  port: 8080

app:
  base-url: http://localhost:8081

hystrix:
  metrics:
    enabled: false
zuul:
  ignore-security-headers: false
  sensitive-headers:
  ignored-patterns:
    - /api/v1/login
    - /api/v1/logout
  routes:
    my-service:
      strip-prefix: false
      path: /api/v1/**
      url: ${app.base-url}
